### ISSUE TITLE
Add early stopping and pruning to hparam search

### ISSUE THREAD

**Issue by sorenhartmann** [sorenhartmann/mlops_project#24]

**Comment by MikkelMathiasen23** [comment]
Early stopping PL module: https://pytorch-lightning.readthedocs.io/en/latest/common/early_stopping.html
Pruning: https://optuna.readthedocs.io/en/v1.0.0/tutorial/pruning.html


Integrate optuna earlystopping callback in pytorch lightning: https://optuna.readthedocs.io/en/v1.0.0/reference/integration.html#optuna.integration.PyTorchLightningPruningCallback

**Comment by idariis** [comment]
Early stopping has been implemented but not pruning. We will look at this Tuesday if the model is still overfitting.
