### ISSUE TITLE
Visualization of optuna results

### ISSUE THREAD

**Issue by MikkelMathiasen23** [sorenhartmann/mlops_project#25]

**Comment by idariis** [comment]
This https://wandb.ai/mlops_project/mlops_project/groups/hparam-search?workspace=default ?

**Comment by MikkelMathiasen23** [comment]
yes could be. Just because i saw this one: 

https://optuna.readthedocs.io/en/latest/tutorial/10_key_features/005_visualization.html

**Comment by idariis** [comment]
<img width="1114" alt="Screenshot 2021-06-21 at 09 42 27" src="https://user-images.githubusercontent.com/46669248/122725156-feee4700-d274-11eb-8d7e-8069931934b0.png">
